- name: Ensure firewalld is installed
  become: true
  package:
    name: firewalld
    state: present

- name: Ensure firewalld is running and enabled
  become: true
  service:
    name: firewalld
    state: started
    enabled: true

- name: Load BBR congestion control module
  become: true
  modprobe:
    name: tcp_bbr
    state: present

- name: Display available congestion control algorithms
  become: true
  command: cat /proc/sys/net/ipv4/tcp_available_congestion_control
  register: congestion_control
  changed_when: false

- name: Show available TCP congestion controls
  become: true
  debug:
    msg: "{{ congestion_control.stdout }}"

- name: Add firewalld rich rules for each source and port
  become: true
  vars:
    sources:
      - "10.140.81.0/24"
      - "10.140.82.0/24"
      - "10.140.83.0/24"
      - "10.52.2.0/24"
      - "10.52.0.0/24"
      - "192.5.87.71"
      - "129.114.108.216"
      - "192.168.210.10"
      - "192.168.210.11"
      - "192.168.230.10"
      - "192.168.230.11"
      - "128.135.11.192"
      - "128.135.164.119"
      - "128.135.24.119"
      - "128.135.24.117"
      - "128.135.164.120"
      - "128.135.24.120"
      - "128.135.24.118"
    ports:
      - "5050-5150"
      - "5200-5300"
      - "5000"
      - "6666-6669"
  loop: "{{ sources | product(ports) | list }}"
  loop_control:
    label: "{{ item.0 }} → {{ item.1 }}"
  firewalld:
    zone: public
    permanent: true
    immediate: false
    rich_rule: "rule family='ipv4' source address='{{ item.0 }}' port port='{{ item.1 }}' protocol='tcp' accept"
    state: enabled

- name: Reload firewalld to apply new rules
  become: true
  command: firewall-cmd --reload

- name: List current rich rules
  become: true
  command: firewall-cmd --zone=public --list-rich-rules
  register: firewalld_rules

- name: Show configured rich rules
  debug:
    msg: "{{ firewalld_rules.stdout_lines }}"
