#double check the commands on linux vms

# Define the Vagrant configuration version
Vagrant.configure("2") do |config|
  # Define the base box (Ubuntu)
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.synced_folder "/home/seena/Projects/globus-stream/scistream-compute/old-scistream/sync/", "/mnt"

  # Copy the wheel file to each VM
  config.vm.provision "file", source: "dist/scistream_proto-1.2.11-py3-none-any.whl", 
destination: "scistream_proto-1.2.11-py3-none-any.whl"


  # Provisioning to install Docker and the Python package
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install -y docker-ce
    sudo apt-get install -y iperf3
    sudo usermod -aG docker vagrant
    sudo apt-get install -y python3-pip
    pip3 uninstall scistream-proto -y
    pip3 install scistream_proto-1.2.11-py3-none-any.whl
    #pip3 install globus-compute-endpoint

    #sudo cp /mnt/keys/* /
    #sudo chown vagrant /server.* 
    #sudo chmod 660 /server.*
    #ls -lah /server.*

    #sudo cp /mnt/keys/* ~/.scistream
    #sudo chown vagrant ~/.scistream/server.* 
    #sudo chmod 660 ~/.scistream/server.*
    #ls -lah ~/.scistream/server.*

    sudo cp /mnt/* .
    sudo chown vagrant ./server.* 
    sudo chmod 660 ./server.*
    ls -lah ./server.*

  SHELL

  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.10.10"
  end

  config.vm.define "p2cs" do |p2cs|
    p2cs.vm.hostname = "p2cs"
    p2cs.vm.network "private_network", ip: "192.168.10.11"
    p2cs.vm.network "private_network", ip: "192.168.20.10"
  end

  config.vm.define "c2cs" do |c2cs|
    c2cs.vm.hostname = "c2cs"
    c2cs.vm.network "private_network", ip: "192.168.20.11"
    c2cs.vm.network "private_network", ip: "192.168.30.10"
  end

  config.vm.define "cons" do |cons|
    cons.vm.hostname = "cons"
    cons.vm.network "private_network", ip: "192.168.30.11"
  end
end
