Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # Ansible provisioner
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "deploy/playbook.yml"
  end

  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.10.10"
  end

  config.vm.define "p2cs" do |p2cs|
    p2cs.vm.hostname = "p2cs"
    p2cs.vm.network "private_network", ip: "192.168.10.11"
    p2cs.vm.network "private_network", ip: "192.168.20.10"
  end

  config.vm.define "c2cs" do |c2cs|
    c2cs.vm.hostname = "c2cs"
    c2cs.vm.network "private_network", ip: "192.168.20.11"
    c2cs.vm.network "private_network", ip: "192.168.30.10"
  end

  config.vm.define "cons" do |cons|
    cons.vm.hostname = "cons"
    cons.vm.network "private_network", ip: "192.168.30.11"
  end
end
